apiVersion: batch/v1
kind: Job
metadata:
  name: cr-status-checker
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      serviceAccountName: cr-status-checker
      containers:
      - image: "cr-status-checker:v0.0.1"
        name: cr-status-checker
        env:
        - name: CUSTOM_RESOURCE_PATH
          value: "apis/pulumi.com/v1/namespaces/default/stacks"
        - name: STATE_KEY
          value: ".items[].status.lastUpdate.state"
        - name: STATE_VALUE
          value: "succeeded"
      restartPolicy: OnFailure
  backoffLimit: 300
