name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/setup-qemu-action@v1.2.0

      - name: Login to GitHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=long
            type=edge,branch=$repo.default_branch
      - name: build+push
        uses: docker/build-push-action@v2.8.0
        with:

          platforms: linux/arm64,linux/amd64,linux/arm/v7,linux/s390x,linux/386,linux/ppc64le
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
